#ifndef DEFINES_H
#define DEFINES_H

#define DEFAULT_WINDOW_WIDTH      600
#define DEFAULT_WINDOW_HEIGHT     400
#define DEFAULT_WINDOW_FULLSCREEN false
#define DEFAULT_WINDOW_TITLE      "Application"

#define DEFAULT_CONTEXT_MAJOR_VERSION 3
#define DEFAULT_CONTEXT_MINOR_VERSION 2

#endif